import { notFound } from "next/navigation";
import { requireModule, userHasAnyRole } from "@/lib/auth/dal";
import { getGuardProfile } from "@/lib/guard/queries";
import { APP_BRAND_SHORT } from "@/lib/config";

export const metadata = { title: "Guard Agency Letter" };

function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-PH", {
    timeZone: "Asia/Manila", year: "numeric", month: "long", day: "numeric",
  });
}

export default async function GuardLetterPage({
  params,
}: {
  params: Promise<{ userId: string }>;
}) {
  const { userId } = await params;
  const user = await requireModule("guard");
  const canManage = userHasAnyRole(user, ["admin", "managing_officer", "consultant"]);
  if (!canManage) notFound();

  const profile = await getGuardProfile(userId);
  if (!profile) notFound();

  const issuedDate = new Date().toLocaleDateString("en-PH", {
    timeZone: "Asia/Manila", year: "numeric", month: "long", day: "numeric",
  });

  return (
    <div className="min-h-screen bg-white">
      {/* Print-only styles */}
      <style>{`
        @media print {
          .no-print { display: none !important; }
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
      `}</style>

      {/* Print button — hidden on print */}
      <div className="no-print mb-6 flex justify-end gap-3 px-8 pt-6">
        <a
          href="/guard/accounts"
          className="rounded-lg border border-stone-300 px-4 py-2 text-sm text-stone-600 hover:bg-stone-50"
        >
          ← Back
        </a>
        <button
          type="button"
          onClick={() => { if (typeof window !== "undefined") window.print(); }}
          className="rounded-lg bg-stone-800 px-5 py-2 text-sm font-semibold text-white hover:bg-stone-900"
        >
          Print / Save PDF
        </button>
      </div>

      {/* Letter body */}
      <div className="mx-auto max-w-[700px] px-8 pb-16 font-serif text-sm leading-relaxed text-stone-900">
        {/* Letterhead */}
        <div className="border-b-2 border-stone-800 pb-4 text-center">
          <p className="text-lg font-bold uppercase tracking-widest">{APP_BRAND_SHORT}</p>
          <p className="mt-0.5 text-xs text-stone-500">
            Security Operations
          </p>
        </div>

        <p className="mt-6 text-right text-xs text-stone-500">{issuedDate}</p>

        <p className="mt-4 font-semibold">To Whom It May Concern:</p>

        <p className="mt-4">
          This letter certifies that{" "}
          <strong>{profile.displayLabel}</strong>
          {profile.guardAgency ? (
            <>, assigned by <strong>{profile.guardAgency}</strong>,</>
          ) : null}{" "}
          is an authorized security guard{" "}
          {profile.guardPosition ? `holding the position of ${profile.guardPosition} ` : ""}
          at {APP_BRAND_SHORT} properties.
        </p>

        <p className="mt-4">
          This individual has been granted access to the property&apos;s security management system
          for the purpose of logging gate entries, monitoring occupancy, and coordinating with
          property management in the performance of their duties.
        </p>

        {profile.guardContractExpiresAt && (
          <p className="mt-4">
            This authorization is valid until{" "}
            <strong>{fmtDate(profile.guardContractExpiresAt)}</strong>.
          </p>
        )}

        {profile.guardNdaAcknowledgedAt && (
          <p className="mt-4">
            The above-named guard has acknowledged the Non-Disclosure and Code of Conduct Agreement
            as of <strong>{fmtDate(profile.guardNdaAcknowledgedAt)}</strong>.
          </p>
        )}

        <p className="mt-6">
          This letter is issued for reference purposes only and is valid as of the date stated above.
        </p>

        <div className="mt-14 grid grid-cols-2 gap-16">
          <div>
            <div className="border-t border-stone-400 pt-2">
              <p className="font-semibold">{APP_BRAND_SHORT}</p>
              <p className="text-xs text-stone-500">Authorized Representative</p>
            </div>
          </div>
          <div>
            <div className="border-t border-stone-400 pt-2">
              <p className="font-semibold">{profile.displayLabel}</p>
              <p className="text-xs text-stone-500">
                {profile.guardPosition ?? "Security Guard"}
                {profile.guardAgency ? ` · ${profile.guardAgency}` : ""}
              </p>
            </div>
          </div>
        </div>

        <p className="mt-10 text-center text-[10px] text-stone-400">
          Generated by {APP_BRAND_SHORT} security management system · {issuedDate}
        </p>
      </div>
    </div>
  );
}
