-- =============================================================================
-- 0108 · INTENTIONALLY NOT APPLIED — AR uniqueness analysis
-- =============================================================================
-- FINDING: ar_no in stay_payments is a physical AR booklet number, not a
-- per-transaction identifier. A single booklet is used for an entire cashier
-- shift, so many transactions legitimately share the same ar_no (verified:
-- AR-204363 used 55×, 204786 used 45×, etc. — all correct, not duplicates).
--
-- The per-transaction unique identifier is receipt_no (OR number), not ar_no.
--
-- DO NOT create a unique index on stay_payments(ar_no).
-- If receipt_no uniqueness enforcement is ever needed, it belongs here instead.
--
-- This file is kept as a documented audit trail of the investigation.
